config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, controllers: {
        sessions: 'admin/sessions'
      }

  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#index'
    get '/customers/my_page' => 'customers#show'
    get '/customers/edit' => 'customers#edit'
    patch '/customers' => 'customers#update'
    get '/customers/unsubscribe' => 'customers#unsubscribe'
    patch '/customers/withdraw' => 'customers#withdraw'
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    resources :items, only: [:index, :show]
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]
    post '/orders/confirm' => 'orders#confirm'
    get '/orders/complete' => 'orders#complete'
    resources :orders, only: [:new, :create, :index, :show]
  end

  devise_for :customers, controllers: {
        sessions: 'public/sessions',
        registrations: 'public/registrations',
        passwords: 'public/passwords'
      }


  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    get '' => 'homes#top'
    resources :order_details, only: [:update]
  end


end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  def shipping_total_name
    "〒" + self.postal_code + ' ' + self.address + ' ' + self.name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy

  def active_for_authentication?
    super && (self.is_active == true)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy

end

app/models/item.rb
class Item < ApplicationRecord

  has_many :order_details, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  belongs_to :genre

  attachment :image

end

app/models/order.rb
class Order < ApplicationRecord

  has_many :order_details, dependent: :destroy
  belongs_to :customer

  enum payment_method:{クレジットカード: 0, 銀行振込: 1}
  enum status:{入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item

  enum making_status:{製作不可: 0, 製作待ち: 1, 製作中: 2, 製作完了: 3}

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  before_action :authenticate_admin!

  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    customer = Customer.find(params[:id])
    customer.update(customer_params)
    redirect_to admin_customer_path(customer.id)
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_active)
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  before_action :authenticate_admin!, only: [:create, :update]


  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    genre = Genre.new(genre_params)
    genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end


end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  before_action :authenticate_admin!

  def top
    @orders = Order.page(params[:page]).reverse_order
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  before_action :authenticate_admin!, only: [:index, :show, :update]

  def index
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
  end

  def create
    item = Item.new(item_params)
    item.save
    redirect_to admin_item_path(item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path(item.id)
  end

  private
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  before_action :authenticate_admin!

  def show
    @order = Order.find(params[:id])
  end

  def update
    order = Order.find(params[:id])
    order.update(order_params)
    if order.status == "入金確認"
      order.order_details.update_all(making_status: "製作待ち")
    end
    redirect_to admin_order_path(order.id)
  end

  private

  def order_params
    params.require(:order).permit(:customer_id, :postal_code, :address, :name, :payment_method, :status, :created_at)
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resources)
    case resources
      when Admin
        admin_path
      when Customer
        root_path
    end
  end

  def after_sign_out_path_for(resource_or_scope)
     return new_admin_session_path if resource_or_scope == :admin
     root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<main>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-9">
        <div class="m-5"></div>
          <h5><span class="ml-5 border px-3 bg-light"><strong>ジャンル編集</strong></span></h5>
          <div class="m-5"></div>
          <%= form_with model:@genre, url:"/admin/genres/#{@genre.id}", local:true do |f| %>
            <div class="row">
              <p class="col-2">ジャンル名</p>
              <div class="col-4">
                <%= f.text_field :name %>
              </div>
              <div class="col-3">
                <%= f.submit '変更を保存', class: 'btn btn-success px-3' %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/admin/genres/index.html.erb
<main>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-9">
        <div class="m-5"></div>
        <h5><span class="ml-5 border px-3 bg-light"><strong>ジャンル一覧・追加</strong></span></h5>
        <div class="m-5"></div>
        <%= form_with model:@genre, url:'/admin/genres', local:true do |f| %>
          <div class="row">
            <p class="col-2">ジャンル名</p>
            <div class="col-4">
              <%= f.text_field :name %>
            </div>
            <div class="col-3">
            <%= f.submit '新規登録', class: 'ml-3 btn btn-success px-3' %>
            </div>
          </div>
        <% end %>
        <div class="m-5"></div>
        <table class="table col-5 border-bottom">
          <thead>
            <tr class="table-secondary">
              <th class="pl-5">ジャンル</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @genres.each do |genre| %>
              <tr>
                <td><span><%= genre.name %></span></td>
                <td><%= link_to "編集する", "/admin/genres/#{genre.id}/edit", class: "btn btn-success ml-5" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/admin/items/edit.html.erb
<main>
  <div class="container">
    <div class="p-4">
      <h5 class="ml-5"><span class="border px-3 bg-light"><strong>商品編集</strong></span></h5>
    </div>

    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <%= form_with model:@item, url:"/admin/items/#{@item.id}", local:true do |f| %>
          <div class="row">
            <p class="col-3">商品画像</p>
            <div class="col-4"><%= f.attachment_field :image %></div>
          </div>
          <div class="row">
            <p class="col-3">商品名</p>
            <div class="col-4"><%= f.text_field :name, size: 30 %></div>
          </div>
          <div class="row">
            <p class="col-3">商品説明</p>
            <div class="col-4"><%= f.text_area :introduction, size: "33x5" %></div>
          </div>
          <div class="row">
            <p class="col-3">ジャンル</p>
            <div class="col-4"><%= f.select(:genre_id, [ ["ケーキ",1], ["プリン", 2], ["焼き菓子", 3 ] ,["キャンディ", 4] ], prompt: "選択してください") %></div>
          </div>
          <div class="row">
            <p class="col-3">税抜き価格</p>
            <div class="col-4"><%= f.text_field :price, size: 30 %></div>
            <p class="col-2 ml-5">円</p>
          </div>
          <div class="row">
            <p class="col-3">販売ステータス</p>
            <div class="col-5"><%= f.radio_button :is_active, "販売中", checked: true %>販売中　 <%= f.radio_button :is_active, "販売停止中" %>販売停止中</div>
          </div>
          <div class="col-5 mx-auto"><%= f.submit '変更を保存', class: 'btn btn-success' %></div>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/admin/items/index.html.erb
<main>
  <div class="container">
    <div class="p-4">
      <div class="row">
        <h5 class="col-3 ml-5"><span class="border px-3 bg-light"><strong>商品一覧</strong></span></h5>
        <div class="col-7 text-right"><%= link_to '+', "/admin/items/new", class: 'btn rounded-circle shadow' %></div>
      </div>
    </div><br />

    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-10 col-xl-8">
        <table class="table border-bottom border-dark">
          <thead>
            <tr class="table-secondary">
              <th class="border-top border-dark">商品ID</th>
              <th class="border-top border-dark">商品名</th>
              <th class="border-top border-dark">税抜価格</th>
              <th class="border-top border-dark">ジャンル</th>
              <th class="border-top border-dark">ステータス</th>
            </tr>
          </thead>
          <tbody>
            <% @items.each do |item| %>
              <tr>
                <td class="border-top border-dark"><span><%= item.id %></span></td>
                <td class="border-top border-dark"><span class="border-bottom border-dark">
                  <%= link_to (admin_item_path(item.id)) do %>
                      <span><%= item.name %></span>
                  <% end %>
                </td>
                <td class="border-top border-dark"><span><%= item.price %></span></td>
                <td class="border-top border-dark"><span><%= item.genre.name %></span></td>
                <td class="border-top border-dark">
                  <% if item.is_active == true %>
                    <p class="text-success"><strong>販売中</strong></p>
                  <% else %>
                    <p class="text-black-50"><strong>販売停止中</strong></p>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <div class="d-flex justify-content-center"><%= paginate @items %></div>
      </div>
    </div>
  </div>
</main>

app/views/admin/items/new.html.erb
<main>
  <div class="container">
    <div class="p-4">
      <h5 class="ml-5"><span class="border px-3 bg-light"><strong>商品新規登録</strong></span></h5>
    </div>
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <%= form_with model:@item, url:"/admin/items", local:true do |f| %>
          <div class="row">
            <p class="col-3">商品画像</p>
            <div class="col-4"><%= f.attachment_field :image %></div>
          </div>
          <div class="row">
            <p class="col-3">商品名</p>
            <div class="col-4"><%= f.text_field :name, size: 30 %></div>
          </div>
          <div class="row">
            <p class="col-3">商品説明</p>
            <div class="col-4"><%= f.text_area :introduction, size: "33x5" %></div>
          </div>
          <div class="row">
            <p class="col-3">ジャンル</p>
            <div class="col-4"><%= f.select(:genre_id, [ ["ケーキ",1], ["プリン", 2], ["焼き菓子", 3 ] ,["キャンディ", 4] ], prompt: "選択してください") %></div>
          </div>
          <div class="row">
            <p class="col-3">税抜き価格</p>
            <div class="col-4"><%= f.text_field :price, size: 30 %></div>
            <p class="col-2 ml-5">円</p>

          </div>
          <div class="row">
            <p class="col-3">販売ステータス</p>
            <div class="col-5"><%= f.radio_button :is_active, "販売中", checked: true %>販売中 　<%= f.radio_button :is_active, "販売停止中" %>販売停止中</div>
          </div>
          <div class="col-5 mx-auto"><%= f.submit '新規登録', class: 'btn btn-success' %></div>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/admin/items/show.html.erb
<main>
  <div class="container">
    <div class="p-4">
      <h5 class="ml-5"><span class="border px-3 bg-light"><strong>商品詳細</strong></span></h5>
    </div>
    <div class="row">
      <div class="col-lg-4">
        <%= attachment_image_tag @item, :image, :fill, 300, 300, format: 'jpeg' %>
      </div>
      <div class="col-lg-6">
        <br />
        <div class="row">
          <p class="col-4">商品名</p><strong class="col-6"><%= @item.name %></strong>
        </div>
        <div class="row">
          <p class="col-4">商品説明</p><strong class="col-6"><%= @item.introduction %></strong>
        </div><br />
        <div class="row">
          <p class="col-4">ジャンル</p><strong class="col-6"><%= @item.genre.name %></strong>
        </div>
        <div class="row">
          <p class="col-4">税込価格<br />(税抜価格)</p><p class="mt-2"><strong class="col-6"><%= (@item.price*1.1).to_i %>(<%= @item.price %>)</strong>円</p>
        </div>
        <div class="row">
          <p class="col-4">販売ステータス</p>
          <% if @item.is_active == true %>
            <strong class="col-6 text-success">販売中</strong>
          <% else %>
            <strong class="col-6 text-black-50">販売停止中</strong>
          <% end %>
        </div>
        <div class="row">
          <div class="col-8 mx-auto mt-2"><%= link_to "編集する", edit_admin_item_path(@item.id), class: 'btn btn-success px-4' %></div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/admin/orders/show.html.erb
<main>
  <div class="container">
    <div class="p-4">
      <div class="row">
        <h5 class="col-3 ml-5"><span class="border px-3 bg-light"><strong>注文履歴詳細</strong></span></h5>
      </div>
    </div><br />
    <div class="col-11">
      <div class="row">
        <div class="col-3"><p><strong>購入者</strong></p></div>
        <div class="col-3"><%= @order.customer.last_name %><%= @order.customer.first_name %></div>
      </div>
      <div class="row">
        <div class="col-3"><p><strong>注文日</strong></p></div>
        <div class="col-2"><%= @order.created_at %></div>
      </div>
      <div class="row">
        <div class="col-3"><p><strong>配送先</strong></p></div>
        <div class="col-5">
          〒<%= @order.postal_code %>　<%= @order.address %><br />
          <%= @order.name %>
        </div>
      </div>
      <div class="row">
        <div class="col-3"><p><strong>支払方法</strong></p></div>
        <div class="col-3"><%= @order.payment_method %></div>
      </div>
      <%= form_with model:@order, url:"/admin/orders/#{@order.id}", local:true do |f| %>
        <div class="row">
          <div class="col-3"><p><strong>注文ステータス</strong></p></div>

          <div class="col-2">
            <%= f.select(:status, [ ["入金待ち","入金待ち"], ["入金確認", "入金確認"], ["製作中", "製作中"], ["発送準備中", "発送準備中"], ["発送済み", "発送済み"] ]) %>
          </div>
          <div class="col-2">
            <%= f.submit '更新', class: 'btn btn-success' %>
          </div>
        </div>
      <% end %>
    </div><br />
    <div class="row">
      <div class="col-9 border-top border-bottom border-dark">
        <div class="row">
          <div class="col-3 border-bottom border-dark pt-3 bg-light"><p><strong>商品名</strong></p></div>
          <div class="col-2 border-bottom border-dark pt-3 pl-0 bg-light"><p><strong>単価(税込み)</strong></p></p></div>
          <div class="col-1 border-bottom border-dark pt-3 pl-0 bg-light"><p><strong>数量</strong></p></div>
          <div class="col-2 border-bottom border-dark pt-3 bg-light"><p><strong>小計</strong></p></div>
          <div class="col-4 border-bottom border-dark pt-3 bg-light"><p><strong>製作ステータス</strong></p></div>
        </div>
        <% @total = 0 %>
        <% @order.order_details.each do |order_detail| %>
          <div class="row">
            <div class="col-3 py-1"><%= order_detail.item.name %></div>
            <div class="col-2 py-1"><%= order_detail.price %></div>
            <div class="col-1 py-1"><%= order_detail.amount %></div>
            <div class="col-2 py-1"><%= order_detail.price*order_detail.amount %></div>
            <div class="col-4 py-1">
              <%= form_with model:order_detail, url:admin_order_detail_path(order_detail), local:true do |f| %>
                <%= f.select(:making_status, [ ["製作不可", "製作不可"], ["製作待ち", "製作待ち"], ["製作中", "製作中"], ["製作完了", "製作完了"] ]) %>
                <%= f.submit "更新", class: 'btn btn-success ml-3' %>
              <% end %>
            </div>
          </div>
          <% @total += (order_detail.item.price*1.1).to_i*order_detail.amount %>
        <% end %>
      </div>
      <div class="col-3"><p class="ml-4 mt-3"><strong>商品合計</strong>　<%= @total %>円</p>
        <p class="ml-4"><strong>送料</strong>　800円</p>
        <p class="ml-4"><strong>請求金額合計　<%= @total+800 %>円</strong></p>
      </div>
    </div>
  </div>
</main>