config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, controllers: {
        sessions: 'admin/sessions'
      }

  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#index'
    get '/customers/my_page' => 'customers#show'
    get '/customers/edit' => 'customers#edit'
    patch '/customers' => 'customers#update'
    get '/customers/unsubscribe' => 'customers#unsubscribe'
    patch '/customers/withdraw' => 'customers#withdraw'
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    resources :items, only: [:index, :show]
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]
    post '/orders/confirm' => 'orders#confirm'
    get '/orders/complete' => 'orders#complete'
    resources :orders, only: [:new, :create, :index, :show]
  end

  devise_for :customers, controllers: {
        sessions: 'public/sessions',
        registrations: 'public/registrations',
        passwords: 'public/passwords'
      }


  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    get '' => 'homes#top'
    resources :order_details, only: [:update]
  end


end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy

  def active_for_authentication?
    super && (self.is_active == true)
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  before_action :authenticate_admin!

  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    customer = Customer.find(params[:id])
    customer.update(customer_params)
    redirect_to admin_customer_path(customer.id)
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_active)
  end

end

app/controllers/customer/confirmations_controller.rb
# frozen_string_literal: true

class Customer::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customer/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customer::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customer/unlocks_controller.rb
# frozen_string_literal: true

class Customer::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<main>
  <div class="container">
    <div class="p-4">
      <h5 class="ml-5"><span class="border px-3 bg-light">
        <strong><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</strong></span>
      </h5>
    </div>

    <div class="col-11">
      <%= form_with model:@customer, url: admin_customer_path(@customer), local:true do |f| %>
      <div class="row">
        <div class="col-3"><p>会員ID</p></div>
        <div class="col-3"><%= @customer.id %></div>
      </div>

      <div class="row">
        <div class="col-3"><p>氏名</p></div>
        <div class="col-3"><%= f.text_field :last_name %></div>
        <div class="col-3"><%= f.text_field :first_name %></div>
      </div>

      <div class="row">
        <div class="col-3"><p>フリガナ</p></div>
        <div class="col-3"><%= f.text_field :last_name_kana %></div>
        <div class="col-3"><%= f.text_field :first_name_kana %></div>
      </div>

      <div class="row">
        <div class="col-3"><p>郵便番号</p></div>
        <div class="col-3"><%= f.text_field :postal_code %></div>
      </div>

      <div class="row">
        <div class="col-3"><p>住所</p></div>
        <div class="col-3"><%= f.text_area :address, :size => "60*10" %></div>
      </div>

      <div class="row">
        <div class="col-3"><p>電話番号</p></div>
        <div class="col-3"><%= f.text_field :telephone_number %></div>
      </div>

      <div class="row">
        <div class="col-3"><p>メールアドレス</p></div>
        <div class="col-3"><%= f.text_field :email %></div>
      </div>

      <div class="row">
        <div class="col-3"><p>会員ステータス</p></div>
        <div class="col-3">
          <%= f.radio_button :is_active, true, checked: true %>有効<%= f.radio_button :is_active, false %>退会
        </div>
      </div><br />

      <div class="row">
        <div class="col-3 offset-3"><%= f.submit '変更を保存', class: 'btn btn-success text-center px-5' %></div>
      </div>
      <% end %>
    </div>
  </div>
</main>

app/views/admin/customers/index.html.erb
<main>
  <div class="container">
    <div class="p-4">
      <div class="row">
        <h5 class="col-3 ml-5"><span class="border px-3 bg-light"><strong>会員一覧</strong></span></h5>
      </div><br />

      <div class="row">
        <div class="mx-auto col-11 col-sm-10 col-lg-10 col-xl-8">
          <table class="table border-bottom border-dark">
            <thead>
              <tr class="table-secondary">
                <th class="border-top border-dark">会員ID</th>
                <th class="border-top border-dark">氏名</th>
                <th class="border-top border-dark">メールアドレス</th>
                <th class="border-top border-dark">ステータス</th>
              </tr>
            </thead>
            <tbody>
              <% @customers.each do |customer| %>
                <tr>
                  <td class="border-top border-dark"><span><%= customer.id %></span></td>
                  <td class="border-top border-dark">
                    <%= link_to(admin_customer_path(customer.id)) do %>
                      <span><%= customer.last_name %><%= customer.first_name %></span>
                    <% end %>
                  </td>
                  <td class="border-top border-dark"><span><%= customer.email %></span></td>
                  <td class="border-top border-dark">
                    <% if customer.is_active == true %>
                      <p class="text-success"><strong>有効</strong></p>
                    <% else %>
                      <p class="text-black-50"><strong>退会</strong></p>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <div class="d-flex justify-content-center"><%= paginate @customers %></div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/admin/customers/show.html.erb
<main>
  <div class="container">
    <div class="p-4">
      <h5 class="ml-5"><span class="border px-3 bg-light">
        <strong><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</strong></span>
      </h5>
    </div>
    <div class="col-11">
      <div class="row">
        <div class="col-3"><p>会員ID</p></div>
        <div class="col-3"><%= @customer.id %></div>
      </div>

      <div class="row">
        <div class="col-3"><p>氏名</p></div>
        <div class="col-2"><%= @customer.last_name %></div>
        <div class="col-2"><%= @customer.first_name %></div>
      </div>

      <div class="row">
        <div class="col-3"><p>フリガナ</p></div>
        <div class="col-2"><%= @customer.last_name_kana %></div>
        <div class="col-2"><%= @customer.first_name_kana %></div>
      </div>

      <div class="row">
        <div class="col-3"><p>郵便番号</p></div>
        <div class="col-3"><%= @customer.postal_code %></div>
      </div>

      <div class="row">
        <div class="col-3"><p>住所</p></div>
        <div class="col-3"><%= @customer.address %></div>
      </div>

      <div class="row">
        <div class="col-3"><p>電話番号</p></div>
        <div class="col-3"><%= @customer.telephone_number %></div>
      </div>

      <div class="row">
        <div class="col-3"><p>メールアドレス</p></div>
        <div class="col-3"><%= @customer.email %></div>
      </div>

      <div class="row">
        <div class="col-3"><p>会員ステータス</p></div>
        <div class="col-3">
          <% if @customer.is_active == true %>
            <p class="text-success"><strong>有効</strong></p>
          <% else %>
            <p class="text-black-50"><strong>退会</strong></p>
          <% end %>
        </div>
      </div><br />

      <div class="row">
        <div class="col-3 offset-3"><%= link_to "編集する", edit_admin_customer_path(@customer.id), class: 'btn btn-success' %></div>
        <div class="col-6"><%= link_to "注文履歴一覧を見る", admin_path, class: 'btn btn-primary' %></div>
      </div>
    </div>
  </div>
</main>